### ISSUE TITLE
Is the backend service down?

### ISSUE THREAD

**Issue by guitaripod** [amakvana/YuzuModDownloader#54]
```
[marcus@arch Downloads]$ ./SwitchEmuModDownloader
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage, CancellationToken)
at SwitchEmuModDownloader.Classes.Downloaders.OfficialSwitchModDownloader.DownloadHtmlDocumentAsync()
at SwitchEmuModDownloader.Classes.Downloaders.OfficialSwitchModDownloader.ReadGameTitlesDatabaseAsync()
at SwitchEmuModDownloader.MainWindow.BtnDownload_ClickAsync(Object sender, RoutedEventArgs e)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
at Avalonia.Threading.DispatcherOperation.Execute()
at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation)
at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
at Avalonia.Threading.Dispatcher.Signaled()
at Avalonia.X11.X11PlatformThreading.CheckSignaled()
at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken)
at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
at SwitchEmuModDownloader.Program.Main(String[])
Aborted (core dumped)
```

**Comment by guitaripod** [comment]
dormant
